language: java
jdk:
  - openjdk11

install:
  - bundle config set --local path 'vendor/bundle'
  - npm install

# Travis Ci를 어느 브랜치가 푸시될 때 수행할지 지정
branches:
  only:
    - develop

# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"